#!/bin/bash
#
# Firefox Build Script for PowerPC Mac OS X Tiger/Leopard
#
# Uses the custom Rust-to-PowerPC compiler (rustc_ppc)
# Target: Firefox ESR (Extended Support Release)
#
# Opus 4.5 - The final frontier!
#

set -e

# ============================================================
# CONFIGURATION
# ============================================================

FIREFOX_VERSION="115.0esr"  # Last ESR with reasonable Rust requirements
FIREFOX_URL="https://archive.mozilla.org/pub/firefox/releases/${FIREFOX_VERSION}/source/firefox-${FIREFOX_VERSION}.source.tar.xz"

# Target configuration
TARGET_TRIPLE="powerpc-apple-darwin8"
TARGET_CPU="7450"  # G4 default, change to 970 for G5
SDK_PATH="/Developer/SDKs/MacOSX10.4u.sdk"

# Our custom compiler
RUSTC_PPC="$(dirname $0)/rustc_ppc"
BUILD_DIR="$(pwd)/firefox-build"
SRC_DIR="$(pwd)/firefox-${FIREFOX_VERSION}"

# Parallel jobs (adjust for your Mac)
JOBS=2  # G4 dual processor
# JOBS=4  # G5 quad

# ============================================================
# HELPER FUNCTIONS
# ============================================================

log() {
    echo "==> $1"
}

error() {
    echo "ERROR: $1" >&2
    exit 1
}

check_prereqs() {
    log "Checking prerequisites..."

    # Check for Xcode/gcc
    if ! command -v gcc &> /dev/null; then
        error "gcc not found. Install Xcode from Tiger DVD."
    fi

    # Check for our Rust compiler
    if [ ! -f "$RUSTC_PPC" ]; then
        log "Building rustc_ppc..."
        gcc -std=c99 -O3 -mcpu=${TARGET_CPU} -maltivec -o rustc_ppc rustc_100_percent.c
    fi

    # Check SDK
    if [ ! -d "$SDK_PATH" ]; then
        error "Tiger SDK not found at $SDK_PATH"
    fi

    log "Prerequisites OK!"
}

# ============================================================
# DOWNLOAD & EXTRACT
# ============================================================

download_firefox() {
    if [ -d "$SRC_DIR" ]; then
        log "Firefox source already exists at $SRC_DIR"
        return
    fi

    log "Downloading Firefox ${FIREFOX_VERSION}..."

    if [ ! -f "firefox-${FIREFOX_VERSION}.source.tar.xz" ]; then
        curl -L -o "firefox-${FIREFOX_VERSION}.source.tar.xz" "$FIREFOX_URL"
    fi

    log "Extracting..."
    tar xf "firefox-${FIREFOX_VERSION}.source.tar.xz"

    log "Firefox source ready!"
}

# ============================================================
# MOZCONFIG - Firefox build configuration
# ============================================================

create_mozconfig() {
    log "Creating mozconfig for PowerPC Tiger..."

    cat > "$SRC_DIR/mozconfig" << 'MOZCONFIG'
# Firefox mozconfig for PowerPC Mac OS X Tiger
# Generated by rust-ppc-tiger build system

# Target
ac_add_options --target=powerpc-apple-darwin8
ac_add_options --host=powerpc-apple-darwin8

# SDK
ac_add_options --with-macos-sdk=/Developer/SDKs/MacOSX10.4u.sdk
ac_add_options --enable-macos-target=10.4

# Compiler flags
export CC="gcc -arch ppc"
export CXX="g++ -arch ppc"
export CFLAGS="-O2 -mcpu=7450 -maltivec -isysroot /Developer/SDKs/MacOSX10.4u.sdk"
export CXXFLAGS="-O2 -mcpu=7450 -maltivec -isysroot /Developer/SDKs/MacOSX10.4u.sdk"
export LDFLAGS="-isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4"

# Custom Rust compiler for PowerPC
export RUSTC="${RUSTC_PPC:-./rustc_ppc}"
export CARGO="${CARGO_PPC:-./cargo_ppc}"
export RUSTFLAGS="-C target-cpu=7450 -C target-feature=+altivec"

# Build options
ac_add_options --disable-debug
ac_add_options --enable-optimize="-O2 -mcpu=7450 -maltivec"
ac_add_options --enable-release

# Disable features not available on Tiger
ac_add_options --disable-crashreporter
ac_add_options --disable-updater
ac_add_options --disable-tests
ac_add_options --disable-debug-symbols
ac_add_options --disable-webrtc
ac_add_options --disable-av1
ac_add_options --disable-eme

# Disable features requiring newer APIs
ac_add_options --disable-sandbox
ac_add_options --disable-accessibility

# Enable AltiVec optimizations
ac_add_options --enable-altivec

# Reduce memory usage during build
mk_add_options MOZ_MAKE_FLAGS="-j2"
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-ppc-tiger

# Application
ac_add_options --enable-application=browser
ac_add_options --with-branding=browser/branding/official
MOZCONFIG

    log "mozconfig created!"
}

# ============================================================
# RUST COMPONENT PATCHES
# ============================================================

patch_rust_components() {
    log "Patching Rust components for PowerPC..."

    cd "$SRC_DIR"

    # Patch 1: Add PowerPC target to mozilla-central's Cargo.toml
    if ! grep -q "powerpc-apple-darwin" Cargo.toml 2>/dev/null; then
        log "Adding PowerPC target to Cargo.toml..."
        cat >> Cargo.toml << 'CARGO_PATCH'

# PowerPC Tiger target (added by rust-ppc-tiger)
[target.powerpc-apple-darwin8]
linker = "gcc"
ar = "ar"
rustflags = ["-C", "target-cpu=7450", "-C", "target-feature=+altivec"]
CARGO_PATCH
    fi

    # Patch 2: Fix webrender for PowerPC (disable SIMD that requires SSE)
    if [ -d "gfx/wr" ]; then
        log "Patching webrender for PowerPC..."

        # Create PowerPC SIMD shim using AltiVec
        cat > "gfx/wr/webrender/src/ppc_simd.rs" << 'PPC_SIMD'
//! PowerPC AltiVec SIMD for WebRender
//! Replaces SSE intrinsics with AltiVec equivalents

#[cfg(target_arch = "powerpc")]
pub mod simd {
    use std::arch::powerpc::*;

    #[inline(always)]
    pub fn f32x4_splat(v: f32) -> vector_float {
        unsafe { vec_splats(v) }
    }

    #[inline(always)]
    pub fn f32x4_add(a: vector_float, b: vector_float) -> vector_float {
        unsafe { vec_add(a, b) }
    }

    #[inline(always)]
    pub fn f32x4_mul(a: vector_float, b: vector_float) -> vector_float {
        unsafe { vec_madd(a, b, vec_splats(0.0f32)) }
    }

    #[inline(always)]
    pub fn f32x4_min(a: vector_float, b: vector_float) -> vector_float {
        unsafe { vec_min(a, b) }
    }

    #[inline(always)]
    pub fn f32x4_max(a: vector_float, b: vector_float) -> vector_float {
        unsafe { vec_max(a, b) }
    }

    #[inline(always)]
    pub fn i32x4_splat(v: i32) -> vector_signed_int {
        unsafe { vec_splats(v) }
    }
}
PPC_SIMD
    fi

    # Patch 3: Fix encoding_rs for big-endian PowerPC
    if [ -d "third_party/rust/encoding_rs" ]; then
        log "Patching encoding_rs for big-endian..."

        # Add big-endian handling
        sed -i.bak 's/#\[cfg(target_endian = "little")\]/#[cfg(any(target_endian = "little", target_arch = "powerpc"))]/g' \
            third_party/rust/encoding_rs/src/*.rs 2>/dev/null || true
    fi

    # Patch 4: Disable parking_lot's x86-specific optimizations
    if [ -d "third_party/rust/parking_lot_core" ]; then
        log "Patching parking_lot for PowerPC..."

        cat > "third_party/rust/parking_lot_core/src/thread_parker/ppc.rs" << 'PPC_PARKER'
//! PowerPC thread parker using pthreads

use std::sync::atomic::{AtomicI32, Ordering};
use std::time::Instant;

pub struct ThreadParker {
    state: AtomicI32,
}

impl ThreadParker {
    pub const fn new() -> Self {
        Self { state: AtomicI32::new(0) }
    }

    pub unsafe fn prepare_park(&self) {
        self.state.store(1, Ordering::Relaxed);
    }

    pub unsafe fn park(&self) {
        while self.state.load(Ordering::Acquire) == 1 {
            // PowerPC: use lwsync for memory barrier
            core::arch::asm!("lwsync", options(nomem, nostack));
            std::thread::yield_now();
        }
    }

    pub unsafe fn unpark(&self) {
        self.state.store(0, Ordering::Release);
    }
}
PPC_PARKER
    fi

    # Patch 5: Fix style/servo for PowerPC
    if [ -d "servo/components/style" ]; then
        log "Patching Servo style for PowerPC..."

        # Disable x86 cache line assumptions
        sed -i.bak 's/CACHE_LINE_SIZE: usize = 64/CACHE_LINE_SIZE: usize = 128/g' \
            servo/components/style/*/mod.rs 2>/dev/null || true
    fi

    log "Rust patches applied!"
}

# ============================================================
# C++ PATCHES FOR TIGER
# ============================================================

patch_cpp_components() {
    log "Patching C++ components for Tiger..."

    cd "$SRC_DIR"

    # Patch 1: Fix missing Tiger headers
    cat > "build/ppc-tiger-compat.h" << 'TIGER_COMPAT'
/* PowerPC Tiger compatibility shims */
#ifndef PPC_TIGER_COMPAT_H
#define PPC_TIGER_COMPAT_H

#include <AvailabilityMacros.h>

/* Tiger doesn't have these newer macros */
#ifndef MAC_OS_X_VERSION_10_5
#define MAC_OS_X_VERSION_10_5 1050
#endif

#ifndef MAC_OS_X_VERSION_10_6
#define MAC_OS_X_VERSION_10_6 1060
#endif

/* Missing from Tiger's stdlib */
#ifndef __has_feature
#define __has_feature(x) 0
#endif

#ifndef __has_extension
#define __has_extension(x) 0
#endif

/* C11 atomics -> OSAtomic on Tiger */
#ifdef __POWERPC__
#include <libkern/OSAtomic.h>

#define atomic_fetch_add(p, v) OSAtomicAdd32(v, (int32_t*)(p))
#define atomic_fetch_sub(p, v) OSAtomicAdd32(-(v), (int32_t*)(p))
#define atomic_load(p) (*(volatile typeof(*(p))*)(p))
#define atomic_store(p, v) do { \
    __asm__ __volatile__("lwsync" ::: "memory"); \
    *(volatile typeof(*(p))*)(p) = (v); \
} while(0)

#endif /* __POWERPC__ */

#endif /* PPC_TIGER_COMPAT_H */
TIGER_COMPAT

    # Patch 2: Fix NSPR for Tiger
    if [ -d "nsprpub" ]; then
        log "Patching NSPR for Tiger..."

        # Add PowerPC atomic operations
        cat >> "nsprpub/pr/include/md/_darwin.h" << 'NSPR_PPC'

/* PowerPC Tiger atomics */
#if defined(__POWERPC__) && !defined(PR_HAVE_ATOMIC_OPS)
#define PR_HAVE_ATOMIC_OPS 1

#include <libkern/OSAtomic.h>

#define _PR_HAVE_ATOMIC_OPS

static inline PRInt32 _PR_AtomicIncrement(PRInt32 *val) {
    return OSAtomicIncrement32(val);
}

static inline PRInt32 _PR_AtomicDecrement(PRInt32 *val) {
    return OSAtomicDecrement32(val);
}

static inline PRInt32 _PR_AtomicSet(PRInt32 *val, PRInt32 newval) {
    PRInt32 old;
    do {
        old = *val;
    } while (!OSAtomicCompareAndSwap32(old, newval, val));
    return old;
}

static inline PRInt32 _PR_AtomicAdd(PRInt32 *ptr, PRInt32 val) {
    return OSAtomicAdd32(val, ptr);
}

#endif /* __POWERPC__ */
NSPR_PPC
    fi

    # Patch 3: Fix NSS for Tiger
    if [ -d "security/nss" ]; then
        log "Patching NSS for Tiger..."

        # Disable unsupported crypto on Tiger
        echo "#define NSS_DISABLE_AVX2 1" >> "security/nss/lib/freebl/mpi/mpi-config.h"
    fi

    log "C++ patches applied!"
}

# ============================================================
# BUILD
# ============================================================

build_firefox() {
    log "Building Firefox for PowerPC Tiger..."

    cd "$SRC_DIR"

    # Set up environment
    export MOZCONFIG="$SRC_DIR/mozconfig"
    export RUSTC="$RUSTC_PPC"
    export PATH="$(dirname $RUSTC_PPC):$PATH"

    # Bootstrap (installs Python dependencies)
    log "Running bootstrap..."
    ./mach bootstrap --no-interactive --application-choice=browser || true

    # Configure
    log "Configuring..."
    ./mach configure

    # Build!
    log "Building (this will take a while)..."
    log "On a G4 dual 1.42GHz: ~8-12 hours"
    log "On a G5 quad 2.5GHz: ~3-4 hours"

    ./mach build -j${JOBS}

    log "Build complete!"
}

# ============================================================
# PACKAGE
# ============================================================

package_firefox() {
    log "Packaging Firefox.app..."

    cd "$SRC_DIR"

    ./mach package

    DMG_PATH=$(find obj-ppc-tiger/dist -name "*.dmg" | head -1)

    if [ -f "$DMG_PATH" ]; then
        log "SUCCESS! Firefox DMG created at:"
        log "  $DMG_PATH"

        # Copy to Desktop
        cp "$DMG_PATH" ~/Desktop/
        log "Copied to Desktop!"
    else
        log "Package created in obj-ppc-tiger/dist/"
    fi
}

# ============================================================
# MAIN
# ============================================================

main() {
    echo "=================================================="
    echo "Firefox for PowerPC Mac OS X Tiger"
    echo "Using rust-ppc-tiger compiler (Opus 4.5)"
    echo "=================================================="
    echo ""

    case "${1:-build}" in
        download)
            check_prereqs
            download_firefox
            ;;
        patch)
            patch_rust_components
            patch_cpp_components
            ;;
        configure)
            create_mozconfig
            ;;
        build)
            check_prereqs
            download_firefox
            create_mozconfig
            patch_rust_components
            patch_cpp_components
            build_firefox
            ;;
        package)
            package_firefox
            ;;
        all)
            check_prereqs
            download_firefox
            create_mozconfig
            patch_rust_components
            patch_cpp_components
            build_firefox
            package_firefox
            ;;
        *)
            echo "Usage: $0 {download|patch|configure|build|package|all}"
            echo ""
            echo "Commands:"
            echo "  download   - Download Firefox source"
            echo "  patch      - Apply PowerPC patches"
            echo "  configure  - Create mozconfig"
            echo "  build      - Build Firefox"
            echo "  package    - Create DMG"
            echo "  all        - Do everything"
            ;;
    esac
}

main "$@"
